version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
      - ./backend/prompts:/app/prompts
    restart: on-failure
    networks:
      - smart-travel-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    restart: always
    networks:
      - smart-travel-network

networks:
  smart-travel-network:
    driver: bridge